# Generated by Django 4.1.7 on 2023-02-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSS_Feed_Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedName', models.TextField()),
                ('title', models.TextField()),
                ('publishedDate', models.DateField()),
                ('link', models.TextField()),
                ('Summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RSS_Feed_Keyowrds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RSS_Feed_Name_Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedName', models.TextField()),
                ('feedIcon', models.TextField()),
            ],
        ),
    ]
