# Generated by Django 4.1.7 on 2023-03-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_rss_feed_temp_alter_rss_feed_database_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rss_feed_name_icon',
            name='feedFrequency_accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rss_feed_name_icon',
            name='feedFrequency_reject',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rss_feed_database',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rss_feed_database',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='rss_feed_keyowrds',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rss_feed_keyowrds',
            name='keywords',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='rss_feed_name_icon',
            name='feedName',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='rss_feed_name_icon',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rss_feed_temp',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rss_feed_temp',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='rss_feed_url',
            name='feedUrl',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='rss_feed_url',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
